### ISSUE TITLE
Can't add tasks or sprints

### ISSUE THREAD

**Issue by yuters** [iRessources/AgileDwarf#4]
I get a bunch of javascript errors,

Loading the page I get this:

Uncaught TypeError: Object [object Object] has no method 'attachEvent' prototype.js:5644
Uncaught TypeError: Object [object Object] has no method 'dispatchEvent' prototype.js:5734
Uncaught TypeError: Object [object Object] has no method 'attachEvent' prototype.js:5653
Uncaught TypeError: Object [object Object] has no method 'setAttribute' prototype.js:2284

Trying to add something, I get these errors:

POST https://mydomain.com/adsprintinl/inplace 500 (Internal Server Error) jquery-1.7.2.min.js:4
POST https://mydomain.com/adtaskinl/create 400 (Bad Request) 

DEPRECATION WARNING: You're trying to create an attribute 'tasks'. Writing arbitrary attributes on a model is deprecated. Please just use `attr_writer` etc. (called from block in list at /usr/share/redmine/plugins/AgileDwarf/app/controllers/adsprints_controller.rb:9)

**Comment by yuters** [comment]
Ok, figured it out. Seems like your plugin is overriding another one : https://github.com/delaitre/redmine_time_tracker ;)

**Comment by yuters** [comment]
I may continue to look at it if I have the time tomorrow. You can put javascript in a `<% content_for :header_tags do %>` and throw a little `jQuery.noConflict()` after that. This should fix issues with other plugins while we wait for a javascript compatibility check like ChiliProject.

**Comment by yuters** [comment]
I removed the other plugins, refactored the way js is loaded and I'm still getting 400 and 500 errors for sprints and tasks. Testing on redmine 2.0.3stable

**Comment by markablov** [comment]
Thanks for information.
Can you show your redmine logs?
It keeps them - %REDMINE_DIR%\log\%RAILS_ENV%.log

**Comment by yuters** [comment]
Error 500 for sprints slider

NoMethodError (undefined method `flatten!' for {"done_ratio"=>"10"}:Hash):
  plugins/AgileDwarf/app/controllers/adtaskinl_controller.rb:74:in`inplace'
  actionpack (3.2.6) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (3.2.6) lib/abstract_controller/base.rb:167:in`process_action'
  actionpack (3.2.6) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (3.2.6) lib/abstract_controller/callbacks.rb:18:in`block in process_action'
  activesupport (3.2.6) lib/active_support/callbacks.rb:469:in `_run__2980672846047394769__process_action__885721195645590360__callbacks'
  activesupport (3.2.6) lib/active_support/callbacks.rb:405:in`__run_callback'
  activesupport (3.2.6) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.6) lib/active_support/callbacks.rb:81:in`run_callbacks'
  actionpack (3.2.6) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.6) lib/action_controller/metal/rescue.rb:29:in`process_action'
  actionpack (3.2.6) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  activesupport (3.2.6) lib/active_support/notifications.rb:123:in`block in instrument'
  activesupport (3.2.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.6) lib/active_support/notifications.rb:123:in`instrument'
  actionpack (3.2.6) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.2.6) lib/action_controller/metal/params_wrapper.rb:206:in`process_action'
  activerecord (3.2.6) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (3.2.6) lib/abstract_controller/base.rb:121:in`process'
  actionpack (3.2.6) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.6) lib/action_controller/metal.rb:203:in`dispatch'
  actionpack (3.2.6) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.6) lib/action_controller/metal.rb:246:in`block in action'
  actionpack (3.2.6) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (3.2.6) lib/action_dispatch/routing/route_set.rb:73:in`dispatch'
  actionpack (3.2.6) lib/action_dispatch/routing/route_set.rb:36:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in`block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `each'
  journey (1.0.4) lib/journey/router.rb:56:in`call'
  actionpack (3.2.6) lib/action_dispatch/routing/route_set.rb:600:in `call'
  rack-openid (1.3.1) lib/rack/openid.rb:98:in`call'
  actionpack (3.2.6) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.1) lib/rack/etag.rb:23:in`call'
  rack (1.4.1) lib/rack/conditionalget.rb:35:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/head.rb:14:in`call'
  actionpack (3.2.6) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/flash.rb:242:in`call'
  rack (1.4.1) lib/rack/session/abstract/id.rb:205:in `context'
  rack (1.4.1) lib/rack/session/abstract/id.rb:200:in`call'
  actionpack (3.2.6) lib/action_dispatch/middleware/cookies.rb:338:in `call'
  activerecord (3.2.6) lib/active_record/query_cache.rb:64:in`call'
  activerecord (3.2.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:473:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/callbacks.rb:28:in`block in call'
  activesupport (3.2.6) lib/active_support/callbacks.rb:405:in `_run__3426037314766106694__call__4381130237497970122__callbacks'
  activesupport (3.2.6) lib/active_support/callbacks.rb:405:in`__run_callback'
  activesupport (3.2.6) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.6) lib/active_support/callbacks.rb:81:in`run_callbacks'
  actionpack (3.2.6) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/remote_ip.rb:31:in`call'
  actionpack (3.2.6) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/show_exceptions.rb:56:in`call'
  railties (3.2.6) lib/rails/rack/logger.rb:26:in `call_app'
  railties (3.2.6) lib/rails/rack/logger.rb:16:in`call'
  actionpack (3.2.6) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.1) lib/rack/methodoverride.rb:21:in`call'
  rack (1.4.1) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.6) lib/active_support/cache/strategy/local_cache.rb:72:in`call'
  rack (1.4.1) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/static.rb:62:in`call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:143:in`pass'
  rack-cache (1.2) lib/rack/cache/context.rb:155:in `invalidate'
  rack-cache (1.2) lib/rack/cache/context.rb:71:in`call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.6) lib/rails/engine.rb:479:in`call'
  railties (3.2.6) lib/rails/application.rb:220:in `call'
  rack (1.4.1) lib/rack/content_length.rb:14:in`call'
  rack (1.4.1) lib/rack/handler/webrick.rb:59:in `service'
  /usr/share/redmine/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/1.9.1/webrick/httpserver.rb:111:in`service'
  /usr/share/redmine/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/1.9.1/webrick/httpserver.rb:70:in `run'
  /usr/share/redmine/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/1.9.1/webrick/server.rb:183:in`block in start_thread'

**Comment by yuters** [comment]
Error 400 is this :

Validation failed: Tracker is not included in the list

**Comment by markablov** [comment]
First problem is fixed by d121ab82e815cf382e1ca4061556d88982d1fdfd
Second one by f13b83a00a282b1d0caf007f043070a0c19db9c1
I have add settings for project.
Please configure plugin to change default tracker.

**Comment by yuters** [comment]
Thanks a lot! 

However it still doesn't work for me but I'm thinking it has something to do with my setup... I had the same problem with backlogs : The config page saves everything in the settings table but redmine is unable to get them... and I don't get any error logs for this.

**Comment by yuters** [comment]
I've switch from ruby 1.9.2 to ruby 1.8.7 and everything works now, it's probably a bug with redmine.
